import { useRef, useState } from "react";
import { CalendarDays, Check, LoaderCircle, Save, Sparkles } from "lucide-react";
import { useContentPlan } from "../features/content-plan/useContentPlan";
import { isPlanComplete, planDate } from "../features/content-plan/contentPlanUtils";
import { ContentMatrix } from "../features/content-plan/components/ContentMatrix";
import { PlanDayEditor } from "../features/content-plan/components/PlanDayEditor";

export function ContentPlanPage({ active, onDirection, onSettings }: { active: boolean; onDirection: () => void; onSettings: () => void }) {
  const plan = useContentPlan(active);
  const [selectedDay, setSelectedDay] = useState(0);
  const editor = useRef<HTMLDivElement>(null);
  const { state, direction, weekStart, focus, items, loading, busy, dirty, selectedVersion, error, notice } = plan;
  const locked = loading || Boolean(busy);
  const complete = isPlanComplete(items);
  const selected = items.find((item) => item.dayIndex === selectedDay);
  const selectedRecord = state?.versions.find((version) => version.version === selectedVersion);
  const showDay = (day: number) => { setSelectedDay(day); editor.current?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  return <section hidden={!active} className="mx-auto max-w-6xl space-y-5">
    <header className="rounded-[28px] border border-[#DDEBD6] bg-gradient-to-br from-white via-[#FFF5F0] to-[#F0F6EA] p-6 sm:p-8">
      <p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#3F8240]"><CalendarDays size={17} /> Bước 03 · Kế hoạch nội dung</p>
      <h2 className="mt-3 text-3xl font-bold text-[#284D31]">Gieo ý tưởng cho một tuần mới.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#748A74]">Từ định hướng đã chốt, Emsen sẽ cùng bạn sắp xếp 7 ngày nội dung có chất riêng, rõ mục đích và vừa sức để bạn có thể thực hiện.</p>
    </header>
    <div className="flex flex-wrap items-end gap-3 rounded-2xl border border-[#DDEBD6] bg-white p-4"><label className="text-xs font-bold">Ngày bắt đầu<input type="date" min="2000-01-01" max="2099-12-25" value={weekStart} disabled={locked} onChange={(event) => plan.changeWeek(event.target.value)} className="ml-3 rounded-xl border border-[#E6D4CE] px-3 py-2 font-normal" /></label><span className="text-xs text-[#748A74]">{planDate(weekStart, 0)} → {planDate(weekStart, 6)}</span><button type="button" onClick={plan.reload} disabled={locked} className="ml-auto rounded-lg px-2 py-2 text-xs font-bold text-[#3F8240]">Tải bản mới nhất</button></div>
    {error && <p role="alert" className="rounded-xl bg-[#EAF6E4] p-4 text-sm text-[#417F40]">{error}</p>}
    {notice && <p role="status" className="rounded-xl bg-[#F0F7EB] p-4 text-sm text-[#466D47]">{notice}</p>}
    {loading && <p role="status" className="flex items-center gap-2 p-5 text-sm"><LoaderCircle size={18} className="animate-spin" /> Đang tải kế hoạch…</p>}
    {state && !direction && <div className="rounded-[24px] border border-[#DDE8D6] bg-[#F5F9F1] p-8 text-center"><h3 className="text-xl font-bold">Một hướng đi rõ ràng, trước một tuần sáng tạo.</h3><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-[#75856E]">Bạn cần chốt định hướng kênh để kế hoạch bám đúng khán giả, giọng điệu và trụ cột nội dung.</p><button type="button" onClick={onDirection} className="mt-5 rounded-xl bg-[#527F56] px-5 py-3 text-sm font-bold text-white">Mở Định hướng</button></div>}
    {state && direction && <>
      <section className="rounded-[24px] border border-[#DDEBD6] bg-white p-5 sm:p-6">
        <div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-lg font-bold">Tuần này bạn muốn tập trung điều gì?</h3><span className="rounded-full bg-[#FFF0EC] px-3 py-1 text-xs font-bold text-[#3F8240]">{dirty ? "Có thay đổi chưa lưu" : selectedRecord ? `Phiên bản ${selectedVersion} · ${selectedRecord.status === "approved" ? "Đã chốt" : "Nháp"}` : "Kế hoạch mới"}</span></div>
        <p className="mt-2 text-xs leading-5 text-[#748A74]">Dựa trên định hướng phiên bản {direction.version}: {direction.brief.goal}</p>
        {state.latestApprovedDirection && state.latestApprovedDirection.id !== direction.id && <button type="button" disabled={locked} onClick={plan.useLatestDirection} className="mt-2 rounded-lg bg-[#FFF3DD] p-2 text-xs font-bold text-[#856B3A]">Có định hướng mới · Bắt đầu lại với phiên bản {state.latestApprovedDirection.version}</button>}
        <label className="mt-4 block text-xs font-bold">Ưu tiên tuần này · không bắt buộc<textarea value={focus} maxLength={2000} disabled={locked} onChange={(event) => plan.editFocus(event.target.value)} rows={2} placeholder="Ví dụ: Giới thiệu series mới, ưu tiên nội dung quay đơn giản trong một buổi…" className="mt-2 w-full rounded-xl border border-[#E6D4CE] bg-[#FFFDF8] px-4 py-3 text-sm font-normal leading-6" /></label>
        <div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" disabled={locked || !state.aiConfigured} onClick={() => void plan.run("generate")} className="inline-flex items-center gap-2 rounded-xl bg-[#284D31] px-5 py-3 text-sm font-bold text-white disabled:opacity-40">{busy === "all" ? <LoaderCircle size={17} className="animate-spin" /> : <Sparkles size={17} />}{selectedVersion ? "Tạo kế hoạch mới bằng AI" : "AI lên kế hoạch 7 ngày"}</button><button type="button" onClick={onSettings} className="rounded-lg px-2 py-2 text-xs font-bold text-[#3F8240]">{state.aiConfigured ? "Cài đặt kết nối AI" : "Thêm Google API key để dùng AI"}</button></div>
        {busy && <p role="status" className="mt-4 flex items-center gap-2 text-sm text-[#3F8240]"><LoaderCircle size={16} className="animate-spin" />{busy === "draft" || busy === "approved" ? "Đang lưu kế hoạch…" : "emsen đang sắp xếp ý tưởng cho bạn…"}</p>}
      </section>
      <ContentMatrix direction={direction} items={items} onSelectDay={showDay} />
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-7" aria-label="Chọn ngày trong kế hoạch">{items.map((item) => <button type="button" key={item.dayIndex} aria-pressed={selectedDay === item.dayIndex} onClick={() => setSelectedDay(item.dayIndex)} className={`min-w-0 rounded-2xl border p-3 text-left ${selectedDay === item.dayIndex ? "border-[#72B65D] bg-[#FFF0EC]" : "border-[#EAD9D2] bg-white hover:bg-[#FBFDF7]"}`}><span className="text-[11px] font-bold text-[#3F8240]">{planDate(weekStart, item.dayIndex)}</span><span className="mt-2 block line-clamp-3 text-xs font-semibold leading-5">{item.title || "Ý tưởng chờ nảy mầm"}</span><span className="mt-2 block text-[10px] text-[#748A74]">{item.platform} · {item.objective}</span></button>)}</div>
      <div ref={editor} className="scroll-mt-6">{selected && <PlanDayEditor item={selected} direction={direction} weekStart={weekStart} disabled={locked} canGenerate={state.aiConfigured && complete} onChange={(patch) => plan.editItem(selectedDay, patch)} onRegenerate={() => void plan.run("generate", selectedDay)} />}</div>
      <section className="flex flex-wrap items-center gap-3 rounded-2xl border border-[#DDEBD6] bg-white p-5"><button type="button" disabled={locked || !complete} onClick={() => void plan.run("draft")} className="inline-flex items-center gap-2 rounded-xl border border-[#C8DBC1] px-4 py-3 text-sm font-bold disabled:opacity-40"><Save size={16} /> Lưu bản nháp</button><button type="button" disabled={locked || !complete || (!dirty && selectedRecord?.status === "approved" && selectedVersion === state.versions[0]?.version)} onClick={() => void plan.run("approved")} className="inline-flex items-center gap-2 rounded-xl bg-[#527F56] px-5 py-3 text-sm font-bold text-white disabled:opacity-40"><Check size={16} /> Chốt kế hoạch</button><p className="text-xs leading-5 text-[#748A74]">{complete ? "Chốt để dùng cho bước viết kịch bản tiếp theo. Chưa tự động đăng bài." : "Điền đủ nội dung cho 7 ngày để lưu hoặc tạo lại một ngày bằng AI."}</p></section>
      <section className="rounded-[24px] border border-[#DDEBD6] bg-white p-5"><h3 className="font-bold">Lịch sử của tuần này</h3><p className="mt-1 text-xs leading-5 text-[#748A74]">Mỗi lần lưu là một phiên bản. Bản cũ giữ nguyên định hướng và Creator DNA tại thời điểm lưu.</p><div className="mt-4 flex flex-wrap gap-2">{state.versions.length === 0 && <p className="text-xs text-[#748A74]">Chưa có phiên bản đã lưu.</p>}{state.versions.map((version) => <button type="button" disabled={locked} aria-pressed={selectedVersion === version.version} key={version.id} onClick={() => plan.selectVersion(version)} className={`rounded-xl border px-3 py-2 text-left text-xs ${selectedVersion === version.version ? "border-[#72B65D] bg-[#FFF0EC]" : "border-[#EAD9D2]"}`}><span className="block font-bold">Phiên bản {version.version} · {version.status === "approved" ? "Đã chốt" : "Nháp"}</span><span className="mt-1 block text-[#748A74]">{version.source === "ai" ? "AI đề xuất" : "Bạn đã lưu"} · {new Date(version.createdAt).toLocaleString("vi-VN")}</span></button>)}</div></section>
    </>}
  </section>;
}
